name: 🥚 Egg Request
description: Suggest a server to build an egg for
title: "[Egg Request]: <Software/Game>"
labels: ["egg request"]
body:
  - type: markdown
    attributes:
      value: |
          Make sure there are no existing egg requests by searching the [repository issues](https://github.com/pelican-eggs/minecraft/labels/egg%20request). Please understand how the panel works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
  - type: dropdown
    id: expand
    attributes:
      label: Does this expand an already existing service
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: input
    id: game-link
    attributes:
      label: Link to a game or software
      placeholder: minecraft.net/factorio.com/etc
    validations:
      required: true
  - type: input
    id: download-link
    attributes:
      label: Links for the download
      description: This needs to be an official link and not one that is hosted on some forum page or a personal Github page. Docker image is not a viable option.
    validations:
      required: true
    validations:
      required: true
  - type: input
    id: instruction-link
    attributes:
      label: Links for the install docs
      description: Link to installation instructions or documentation covering required dependencies and configuration for the server creation. Docker image is not installation documentation!
    validations:
      required: true
